name: seak
dependencies:
    - python>=3.5
    - mkl==2019.4 # needed for FaST-LMM build
    - scipy
    - numpy
    - cython
    - pip
    - pip:
        - sphinxcontrib-bibtex
        - sphinx-rtd-theme
        - sphinx>=1.3
